project:
  type: website
  output-dir: docs

website:
  title: "David Grayson"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Arial
