project:
  type: website
  output-dir: docs

website:
  title: "David Grayson"
  site-url: "https://davegrays.github.io"
  site-path: "/"
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - href: about.qmd
        text: About


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: Arial
