---
title: "Culture and skepticism"
date: "2023-02-14"
categories:
---

A while back I read Sam’s Harris’ short book titled “Lying.” It deals with all the ways in which people, in everyday life, skirt the truth with each other. It argues that even the smallest lies we tell each other, for example “white lies” and lies of omission, might not be so small. Harris claims that these kinds of fibs are virtually always detrimental on the whole. I won’t go into all the reasoning behind that, or whether I agree, but it got me thinking more broadly about the tension between objective truth and social norms. It occurred to me that there are other types of social norms, apart from those that explicitly enable dishonesty, that may also end up cheating us out of a clearer understanding of ourselves, and of the world around us.

Years ago, I was at a gathering with friends and friends of friends. At some point, we went around and each person described some past story or future aspiration that mattered on a personal level. One person, Robert, recounted a recent conversation with an acquaintance that he hoped to be better friends with, and who considered himself to be pretty knowledgeable about geology. According to Robert, this acquaintance asserted some supposed geological facts that seemed questionable, and Robert's curiosity and skepticism drove him to ask deeper and deeper questions. Eventually, the acquaintance became frustrated and upset, feeling that his expertise was being questioned. They both left the conversation feeling dissatisfied, neither apologizing or attempting to reconcile in the moment. Later, Robert took the initiative to apologize.

Robert framed this as an example of personal growth, in which he learned to prioritize a relationship he cared about by swallowing his pride. Everyone nodded, affirming him for taking the bold step of making himself vulnerable.

I disagreed, so I offered my challenge to the room. Isn't Robert being praised for renouncing an intellectually constructive habit? If his conversation partner actively prevented dialogue, shouldn’t that be seen as destructive? My challenge was dismissed, and I was not surprised. Most everyone agreed it was more or less natural and justified to feel offended when you are interrogated about something you believe you have an expertise in. Moreover, if you want to make friends and keep friends, you have to put your ego aside sometimes.

From my view, this kind of attitude permeates our culture. So the thinking goes, when relationships are at stake, you can’t be too much of a stickler. Being permissive is being practical and considerate. And if someone is personally invested in some version of the truth, that’s a minefield you might not want to march through. Practical indeed. Considerate? I'm not so sure. Cynical? Definitely.

This attitude strikes me as a consequence of a pervasive kind of social taboo - that is, of challenging someone’s beliefs in a social setting. The corollary to this taboo is a status quo which deems that we ought to tolerate all beliefs that are central to anyone’s identity (assuming they're not outrightly offensive). It’s a status quo that’s as contemptible as it is difficult to subvert. Who can deny the awkwardness they feel during Thanksgiving dinner when an aunt or uncle starts up about conspiracy theories or pseudoscience quackery? Who hasn’t sat silent or tried to abruptly change the subject at that moment, out of convenience? The problem only worsens when it’s someone you are close to or depend upon.

We decline to challenge others’ beliefs because it’s unpleasant. But this can be a path-of-least-resistance fallacy where we avoid social discomfort only to end up in an even worse place. For example, sitting silent or changing topics with our gullible relatives certainly would not have helped to curb the other pandemic that was happening simultaneously with COVID - the pandemic of conspiracy theory lunacy about COVID (i.e. that it wasn’t real, or wasn’t dangerous, or that the vaccines weren’t helpful, or that onions cure COVID). People died from COVID, yes, but many thousands (millions?) also died from this lunacy.

Intellectual honesty takes work. Knowledge takes work. Approving others’ questionable beliefs is helpful for building loyalty but not very useful for helping each other refine our understanding of the world. What if, instead of being preoccupied with loyalty, we encouraged each other to see skepticism as friendly and collaborative?

There are examples that show that this kind of shift in cultural expectations is possible. One that comes to mind is the concept of “cooperative overlapping", a conversational style marked by frequent interrupting. Basically, each conversation partner attempts to grasp the other's idea as quickly as possible and interrupts as a way to signal their understanding and build upon it (this is prominent for example in northeastern jewish culture). While much of western culture would take any form of interruption as a sign of disrespect, in the in-group it is quite the contrary. It is appreciated as a sign of mutual engagement.

That's not to say I particularly like that style of conversation. I also don't think that the goal of factual integrity should determine the outcome of most conversations. Most conversations are not about promulgating a set of facts.

The point is that cultural expectations can always be noticed, felt, and re-examined. So what if we re-examined our expectations about whether people should believe the things we say when we DO claim to know about a set of facts? We reach real understanding by going through the process of questioning assumptions, validating those assumptions, questioning the credibility of sources, and validating those sources. In order to go through that process, we have to collectively lean towards being skeptical of others’ claims and of our own. By prioritizing loyalty and by obfuscating the limits of our knowledge, we deny each other this process. In doing so, we botch opportunities left and right to arrive at better, more robust, more nuanced representations of what we do know and a more honest picture of what we don’t. We hold the truth hostage from each other over the fear of puncturing our own thin skin.

In my imagination, we all might be better off if the status quo was more or less the opposite of the reaction I heard to Robert’s story. What if Robert didn’t fear losing any friends over his skepticism, and instead found that people actually gravitated towards that skepticism? What if doubt was sexy? What if humility was sexy? What if we lived in a world where we all agreed that Robert should lean *further* into his curiosity?
