---
title: "Clueless and superstitious"
date: "2023-09-10"
categories:
---

Scientific research is inherently enigmatic. We are asked to endeavor towards future discoveries, despite not knowing what they will be or their precise impact. Consider the discovery of DNA. Its existence was revealed back in the 19th century, though its physical structure and its role in heredity were not properly understood for another 80 years.

We could look even further back. In the dark ages, the existence of the cell, and its crucial role as one of the building blocks of life, would not be known for centuries to come. After its eventual discovery, germ theory wouldn’t come about until hundreds of years after *that*. This total ignorance eventually came to terrorize western civilization during the Black Death, when somewhere around half of Europe's population perished. That tragedy was undoubtedly made worse by unsanitary conditions and superstitious practices, like bloodletting and boil-lancing, that promoted the spread of pathogens.

Nowadays, we live in an era of the most impressive scientific and technological advances humanity has ever seen. The acceleration of new technology gives a sense that perhaps we no longer live in a period of total darkness about anything. For example, we now have a much more thorough understanding of infectious diseases and their associated microbiology. Compare the failure of human effort during the Black Death with what we accomplished during our most recent global pandemic. Within just months after the appearance of a totally novel pathogen, its chemical structure had already been discovered, and testing had already begun on multiple highly effective vaccines. That certainly makes it feel like we have leapt out of the darkness.

The problem is, it’s easy to imagine people in just about any era being thoroughly impressed by the technology of their time. The dark ages saw the invention of the windmill, which automated agricultural labor, and of glasses, among other technologies that would have fundamentally changed lives and livelihoods. Universities themselves arose in the dark ages. So did algebra. I suppose that must have all seemed pretty cutting edge. And yet, when most of Europe was dying with lymph nodes swollen out the sides of their necks, and one of the prevailing theories was divine punishment, it was still several hundreds of years before anyone had a clue as to actually why.

So what, then, might *we* be totally in the dark about? What tragedies have we endured, or are presently enduring, that we are scientifically clueless and often superstitious about?
